### PR TITLE
Decoder tests: Apply base65536's format everywhere

### PR DESCRIPTION
**Pull request by gregorni**
It seems some tests still use the older layout. I don't know if that's on purpose or not, if not here's the PR to fix that.

### CODE REVIEW

**Comment by gregorni** [comment]
What does this error mean?
image

It's the only error, but it's popping up everywhere

**Comment by bee-san** [comment]
> What does this error mean? image
> 
> It's the only error, but it's popping up everywhere

The linter updated :(

Clippy added a new linting rule that ///! should be replaced with //!
because  ///! doesn't mean anything in Rust but //! does.

I think find + replace on every file should work

**Comment by gregorni** [comment]
Ah, okay, easy enough

**Comment by gregorni** [comment]
Alright, so the formatter now tells me to use `///` in some places instead of `//!`. Should I just do that?

Also, in the places where I replaced `///!` with `//!`, I now get errors about `expected outer doc comment`.

**Comment by bee-san** [comment]
Cargo check fails :(

**Comment by gregorni** [comment]
Alright, how do I do a doc comment that pleases the latest version of cargo?

**Comment by gregorni** [comment]
Nevermind

**Comment by gregorni** [comment]
Alright, the CI is fixed now.

**Review by bee-san — APPROVED** [review]

**Pull request merged**
